type move = {
  input: string,
  startup: string,
  startupValue: number,
  hitLevel: string,
  damage: number,
  blockFrame: string,
  blockFrameValue: number,
  hitFrame: string,
  hitFrameValue: number,
  chFrame: string,
  chFrameValue: number,
  balconyBreak?: boolean,
  notes?: string,
}